spring:
  application:
    name: Ling-AI-CODE-generation-backend
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ling.lingaicodegeneration.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

#redisson:
  #onfig: |
    #singleServerConfig:
      #address: "redis://localhost:6379"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always